### ISSUE TITLE
netflix throws UI3010 error

### ISSUE THREAD

**Issue by nishantjain91** [vladikoff/netflix-1080p-firefox#31]
Netflix is giving ui3010 error but if I disable the plugin , it starts working

**Comment by Multipanda** [comment]
Seems like Netflix made a change within the last day, I cant use the plugin either, tested both with 1.7 and 1.9, and it happens both with the newest Firefox 69.0, as well as the previous one.

**Comment by slashmaxx** [comment]
Same error ID given here. FF 69.0 and plugin version 1.8

**Comment by fcoriverah** [comment]
Same here ):

**Comment by panzi** [comment]
Same here. :( Any way I can help to get this fixed?

**Comment by lu5jzz** [comment]
Same here and same error. I use chrome browser for whatch netflix on 1080p momentarily but, the quality of image is not than good that firefox browser :(  .

**Comment by linux-netflix-user** [comment]
I managed to get 1080p again with these changes: https://github.com/vladikoff/netflix-1080p-firefox/pull/32

**Comment by anmolvrm** [comment]
> 
> 
> I managed to get 1080p again with these changes: #32

Can you please share your signed version please?

**Comment by hashar** [comment]
That is definitely fixed by PR #32 and this issue should be marked solved.

To get the latest version packaged as an extension, see #28

**Comment by jakejarvis** [comment]
Thank you **_so_** much @linux-netflix-user! Working great now.

Feel free to delete this comment if posting this is discouraged but here's an exact clone (except with a bumped version number) that's signed: https://x.jarv.is/netflix_1080p-1.9c-an+fx.xpi (@anmolvrm) 

If you don't trust me as a random stranger on the internet (which you shouldn't, to be honest!) then @hashar's steps at the end of #28 work perfectly. :)

**Comment by vaindil** [comment]
@jakejarvis I just tried the XPI in your comment and I still get UI3010. I tried building it myself, but it fails validation because `cadmium-playercore-1080p.js` is too large to parse.

**Comment by jakejarvis** [comment]
@vaindil hmm, my only thought is to check if you have *any* of the older versions still installed, either from the official add-on store (RIP) or signed by other random people on GitHub? Even though these are "updates" they're technically different extensions so they won't replace each other when you add them.

As for building, that's really strange... running `npm install` inside the cloned directory will give you a pretty outdated version of `web-ext` (v2.4.x vs [v3.1.1](https://github.com/mozilla/web-ext/releases)) which might be why... Here are the exact steps I ran to install the latest version globally:

```bash
npm install --global web-ext
```

...and then sign the extension:

```bash
git clone https://github.com/vladikoff/netflix-1080p-firefox/
cd netflix-1080p-firefox
cd src    # be extra sure you're in /src, not just the cloned repo!
web-ext sign --api-key "user:xxxxxx:yyy" --api-secret "zzzzzzzz"
```

After that you should have a `.xpi` file dropped into `netflix-1080p-firefox/src/web-ext-artifacts/netflix_1080p-X.X-an+fx.xpi`. Let me know if that didn't fix anything :)

**Comment by vaindil** [comment]
@jakejarvis I'm sorry, I deleted my original comment somewhat quickly because I refreshed the Netflix page a few times and it ended up working. Thank you, I really appreciate it!

**Comment by jakejarvis** [comment]
@vaindil no problem at all, I'm sure it'll help someone else at some point! 👍

**Comment by hashar** [comment]
I think the cadium player javascript file is stored in cache and thus might not be invalidated when upgrading the extension. It might be worth clearing your local cache.

**Comment by pamposzek** [comment]
@jakejarvis Thanks a lot, your version works nicely!

**Comment by fcoriverah** [comment]
> 
> 
> @vaindil hmm, my only thought is to check if you have _any_ of the older versions still installed, either from the official add-on store (RIP) or signed by other random people on GitHub? Even though these are "updates" they're technically different extensions so they won't replace each other when you add them.
> 
> As for building, that's really strange... running `npm install` inside the cloned directory will give you a pretty outdated version of `web-ext` (v2.4.x vs [v3.1.1](https://github.com/mozilla/web-ext/releases)) which might be why... Here are the exact steps I ran to install the latest version globally:
> 
> ```shell
> npm install --global web-ext
> ```
> 
> ...and then sign the extension:
> 
> ```shell
> git clone https://github.com/vladikoff/netflix-1080p-firefox/
> cd netflix-1080p-firefox
> cd src    # be extra sure you're in /src, not just the cloned repo!
> web-ext sign --api-key "user:xxxxxx:yyy" --api-secret "zzzzzzzz"
> ```
> 
> After that you should have a `.xpi` file dropped into `netflix-1080p-firefox/src/web-ext-artifacts/netflix_1080p-X.X-an+fx.xpi`. Let me know if that didn't fix anything :)

Thanks man!

**Comment by fcoriverah** [comment]
> 
> 
> Thank you **_so_** much @linux-netflix-user! Working great now.
> 
> Feel free to delete this comment if posting this is discouraged but here's an exact clone (except with a bumped version number) that's signed: https://x.jarv.is/netflix_1080p-1.9c-an+fx.xpi (@anmolvrm)
> 
> If you don't trust me as a random stranger on the internet (which you shouldn't, to be honest!) then @hashar's steps at the end of #28 work perfectly. :)

Thanks for the .xpi file! :D working!

**Comment by okradonkey** [comment]
@jakejarvis  I appreciate you hosting a working xpi, but I'm trying to learn how to sign one for myself and I'm running into a problem and could use a hand.  I got through most of the steps but the `web-ext sign` command fails, and the Validation Results link from the error says "File is too large to parse" because cadmium-playercore-1080p.js is >4 MB.  I found a few old related discussions/issues about the Mozilla [addons-linter](https://github.com/mozilla/addons-linter/issues/1248) but no solutions.  Any ideas what I could do differently to get this signed?

**Comment by okradonkey** [comment]
Answering myself:
> "File is too large to parse" because cadmium-playercore-1080p.js is >4 MB.  

For some reason, `git clone` replaced all the LF's in `cadmium-playercore-1080p.js` with CRLF's, and that was enough to increase the file size to just over Mozilla's hard limit of 4 MB.  The file as hosted on github, which uses LF's, is just barely under 4 MB.  So, after replacing the file in my local repository with a direct download from github, I was able to get it signed.  Why this happened is beyond me, but perhaps it's a good canary warning that if cadmium-playercore-1080p.js grows any more in future versions, Mozilla's 4MB limit might become a legitimate problem.  Anyway, problem solved for now!

**Comment by ptramsey** [comment]
Built and installed as of PR #32.  I am seeing a syntax error in cadmium-playercore-1080p.js:

<img width="1131" alt="Screen Shot 2019-09-24 at 8 51 38 PM" src="https://user-images.githubusercontent.com/1173282/65568014-22a02400-df0d-11e9-83bf-aac6a00f04c4.png">

**Comment by ptramsey** [comment]
[](url)

> > Thank you **_so_** much @linux-netflix-user! Working great now.
> > Feel free to delete this comment if posting this is discouraged but here's an exact clone (except with a bumped version number) that's signed: https://x.jarv.is/netflix_1080p-1.9c-an+fx.xpi (@anmolvrm)
> > If you don't trust me as a random stranger on the internet (which you shouldn't, to be honest!) then @hashar's steps at the end of #28 work perfectly. :)
> 
> Thanks for the .xpi file! :D working!
Installed this exact xpi; got "SyntaxError: expected expression, got ']'" on the same line of the same file.  I have no other extensions installed, and am running Firefox 69.0.1.  Any idea what might be going on?
